---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name: ["wget", "tar", "gzip"]
        state: present
      become: true

    - name: Include role
      ansible.builtin.include_role:
        name: "internal.vector_role"
