---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  enabled: false

driver:
  name: podman

platforms:
  - name: almalinux-9
    image: quay.io/almalinux/almalinux:9
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      become: true

verifier:
  name: ansible

scenario:
  name: tox
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - destroy
